# Generated by Django 4.0.4 on 2022-04-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='destinatiom',
            new_name='distance',
        ),
    ]
